eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: zuul-gateway
  rabbitmq:
    host: 192.168.1.111
    port: 5672
    virtual-host: /
    username: root
    password: 123456
  sleuth:
    sampler:
      percentage: 1.0
server:
  port: 8777
zuul:
  routes:
    api-user:
      path: /api/user/**
      serviceId: glgg-user
    api-msg:
      path: /api/msg/**
      serviceId: glgg-msg
