eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: zipkin-server
  rabbitmq:
    host: 192.168.1.111
    port: 5672
    username: root
    password: 123456
    virtual-host: /
server:
  port: 9777