spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/fudongri/spring-cloud-glgg
          search-paths: /config-repo/*
          #username:
          #password:
server:
  port: 8888
