server:
  port: 6777

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/fudongri/spring-cloud-glgg
          search-paths: /config-repo/*
          #username:
          #password:
  rabbitmq:
    host: 192.168.1.111
    port: 5672
    username: root
    password: 123456

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  security:
    enabled: false